### ISSUE TITLE
Añadir imágenes al repositorio

### ISSUE THREAD

**Issue by YolandaRE** [mapereztorres/FIJI-repro#1]
@ElenaIPBLN  tiene que añadir las imágenes al repositorio.

**Comment by jmoldon** [comment]
Veo que ya has subido una imagen, muy chula! Tal vez podrías ponerla en formato jpg o png el README principal del repositorio para que todos la ven fácilmente.

![cells](https://user-images.githubusercontent.com/1053066/164541715-ef43b6df-c610-42c3-a495-6ff7a9ecb7e3.png)

**Comment by jmoldon** [comment]
Por cierto, hace unos años estuve colaborando en un proyecto que tenía como objetivo medir el ritmo de crecimiento bacteriano en cápsulas de petri analizando imágenes de forma automática: https://github.com/vektorious/lightM Supongo que no tiene mucho que ver con este proyecto, pero me ha hecho gracia.

**Comment by ElenaIPBLN** [comment]
Hola! bueno he cogido una muy sencillita y los valores no van a cambiar mucho 
de una célula a otra al ser los núcelos pero para el propósito creo que vale, 
:). Puedo guardar una copia en jpg, pero para analizarla es mejor el tiff. Es 
muy importante que la imagen este calibrada, es decir que lleve la información 
del microscopio, objetivo usado y zoom utilizado, para que luego los valores 
en micras del área sean reales.  De hecho tengo que comprobar que no lo he 
perdido información al dejarla solo como una foto. Es que en el confocal yo 
tomo muchas fotos de una misma célula, es decir si la célula fuera un 
edificio...yo tomo fotos de todas las plantas del edificio...como todos los 
planos. pero lo que os he puesto es una proyección máxima de todos esos stacks 
para simplificar el análisis.  como si observase el edificio desde arriba...

Ayer también intente subir la carpeta del programa pero era demasiada 
pesada...




On Thu, 21 Apr 2022 12:52:56 -0700, Javier Moldon wrote
> Veo que ya has subido una imagen, muy chula! Tal vez podrías 
> ponerla en formato jpg o png el README principal del repositorio 
> para que todos la ven fácilmente.
> 
> ![cells](https://user-images.githubusercontent.com/1053066/164541715-
> ef43b6df-c610-42c3-a495-6ff7a9ecb7e3.png)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mapereztorres/FIJI-repro/issues/1#issuecomment-
> 1105692577
 You are receiving this because you were assigned.
> 
> Message ID: ***@***.***>


Elena Fernandez, PhD 
Instituto de Parasitologia y Biomedicina "Lopez-Neyra"
Avda. Conocimiento S/N
Parque Tecnologico Ciencias de la Salud
18100 Armilla - GRANADA
Spain
Tlf: 958181621
Fax: 958181632
http://www.ipb.csic.es
--
Open WebMail Project (http://openwebmail.org)
